= Collection of Typst Templates

All templates in this repository are made by me under my free time.

== Templates

This repository is a collection of Typst templates for various purposes, check each template for more details:

* link:koma-script[KOMA-Script] (WIP): KOMA-Script classes port to Typst (article/report/book).

=== Versatile APA

.Gallery
* link:versatile-apa.pdf[Default]
* link:versatile-apa-student.pdf[Student]
* link:versatile-apa-professional.pdf[Professional]

=== UPSA Bolivia

.Gallery
* link:upsa-bo-estudio-de-factibilidad.pdf[Estudio de Factibilidad]
* link:upsa-bo-tfg.pdf[Trabajo Final de Grado, facultad de ingeniería]

=== ACM Suite

.Gallery
* link:acm-suite-small.pdf[Small]

=== LaTeX Standard Classes

.Gallery
* link:latex-reborn-article.pdf[Article]
* link:latex-reborn-report.pdf[Report]
* link:latex-reborn-book.pdf[Book]
* link:latex-reborn-letter.pdf[Letter]

=== Butterick’s Résumé

.Gallery
* link:butterick-resume.pdf[Default]

== Usage

You can use these templates in your projects in several ways, depending on your experience and needs:

=== Download or Copy

If you don’t use Git, you can simply:

* Click the green "`Code`" button on GitHub and select "`Download ZIP`".
* Extract the ZIP file and copy the template folder(s) you want into
your project.

=== Using Git

==== Cloning the Repository

If you want all templates, run:

[source,sh]
----
git clone https://github.com/jassielof/typst-templates.git template
----

This creates a folder called `template` with all templates inside.

____
*Note:* If your project is also a Git repository, avoid copying the
`.git/` directory from the template to prevent conflicts.
____

==== Using Submodules

If your project is already a Git repository and you want to keep the
template updated easily, add it as a submodule:

[source,sh]
----
git submodule add https://github.com/jassielof/typst-templates.git template
----

This links the template folder to this repository.

*To update the template later, run:*

[source,sh]
----
git submodule update --remote --merge
----

in your project root. This fetches the latest changes from the template
repository.

*If you clone a project that already uses this submodule, use:*

[source,sh]
----
git clone --recurse-submodules <your-repo-url>
----

or, if you already cloned:

[source,sh]
----
git submodule update --init --recursive
----

____
*Tip:* After updating a submodule, always commit the submodule pointer
in your main repository:

[source,sh]
----
git add template
git commit -m "Update template submodule"
----
____

== Troubleshooting & Tips

* If you see a "`detached HEAD`" warning in the submodule, you can checkout to the main branch inside the submodule:
+
[source,sh]
----
cd template
git checkout main
----
* For more on submodules, see https://git-scm.com/book/en/v2/Git-Tools-Submodules[Git Tools - Submodules].
* If you have questions or issues, feel free to open an issue on this repository!

== License

The repository is licensed under the link:LICENSE.txt[Apache 2.0 License].

Any of the templates found here default to the same license, unless specified otherwise in its respective folder, README, LICENSE or Typst manifest
