version: "3"

tasks:
  default:
    desc: Builds all templates
    deps:
      - versatile-apa
      - latex-reborn
      - acm-suite
      - upsa-bo
      - butterick
  versatile-apa:
    dir: versatile-apa
    env:
      TYPST_ROOT: .
    cmds:
      - typst compile template/main.typ
      - typst compile template/student.typ
      - typst compile template/professional.typ
    desc: Versatile APA Template
    aliases:
      - apa
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
      - "*.png"
  latex-reborn:
    aliases:
      - latex
    dir: latex-reborn
    env:
      TYPST_ROOT: .
    cmds:
      - for: ["report", "article", "book", "letter"]
        cmd: typst compile template/{{.ITEM}}.typ
      - for: ["report", "article", "book", "letter"]
        cmd: typst compile template/{{.ITEM}}.typ thumbnail-{{.ITEM}}.png --pages 1
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
  acm-suite:
    aliases:
      - acm
    dir: acm-suite
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
      - "*.png"
    vars:
      FORMATS: [
          "small",
          # TODO: Enable each one of these once they start to work.
          # "large",
          # "manuscript",
          # "sigpl",
          # "sig-conf",
          # "tog",
          # "cover-page",
          # "engage-cs-edu",
        ]
    cmds:
      - for: { var: FORMATS }
        cmd: typst compile --root . template/{{.ITEM}}.typ # Manuscript is default for thumbnails
      - for: { var: FORMATS }
        cmd: typst compile --root . template/{{.ITEM}}.typ thumbnail-{{.ITEM}}.png --pages 1
      # Manuscript is the default
      # TODO: Enable once it works
      # - typst compile --root . template/manuscript.typ thumbnail.png --pages 1
  upsa-bo:
    dir: upsa-bo
    aliases:
      - upsa
    # watch: true
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
    cmds:
      - for: ["Estudio de Factibilidad", "TFG"]
        cmd: typst compile --root . "template/{{.ITEM}}/{{.ITEM}}.typ"
  butterick:
    dir: butterick-resume
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
      - "*.png"
    cmds:
      - typst compile --root . template/main.typ
      - typst compile --root . template/main.typ thumbnail.png --pages 1
  www:
    desc: Move generated PDFs for deployment
    deps:
      - default
    cmds:
      - mkdir -p www
      - |
        mv versatile-apa/template/main.pdf www/versatile-apa.pdf
        mv versatile-apa/template/student.pdf www/versatile-apa-student.pdf
        mv versatile-apa/template/professional.pdf www/versatile-apa-professional.pdf
      - mv butterick-resume/template/main.pdf www/butterick-resume.pdf
      - |
        mv "upsa-bo/template/Estudio de Factibilidad/Estudio de Factibilidad.pdf" www/upsa-bo-estudio-de-factibilidad.pdf
        mv "upsa-bo/template/TFG/TFG.pdf" www/upsa-bo-tfg.pdf
      - mv "acm-suite/template/small.pdf" www/acm-suite-small.pdf
      - |
        mv latex-reborn/template/report.pdf www/latex-reborn-report.pdf
        mv latex-reborn/template/article.pdf www/latex-reborn-article.pdf
        mv latex-reborn/template/book.pdf www/latex-reborn-book.pdf
        mv latex-reborn/template/letter.pdf www/latex-reborn-letter.pdf
