version: "3"

tasks:
  versatile-apa:
    cmd: typst compile --root versatile-apa versatile-apa/template/main.typ
  versatile-apa-dev:
    cmd: typst watch --root versatile-apa versatile-apa/template/main.typ
  latex-reborn:*:
    cmd: typst compile --root latex-reborn latex-reborn/template/{{.LATEX_REBORN_TEMPLATE}}.typ
    vars:
      LATEX_REBORN_TEMPLATE: "{{index .MATCH 0}}"
  latex-reborn-dev:*:
    cmd: typst watch --root latex-reborn latex-reborn/template/{{.LATEX_REBORN_TEMPLATE}}.typ
    ignore_error: true
    interactive: true
    vars:
      LATEX_REBORN_TEMPLATE: "{{index .MATCH 0}}"
