version: "3"

tasks:
  versatile-apa:
    dir: versatile-apa
    cmd: typst compile --root . template/main.typ
    desc: Versatile APA Template
    aliases:
      - apa
    watch: true
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
  latex-reborn:
    aliases:
      - latex
    # watch: true
    dir: latex-reborn
    cmds:
      - for: ["report", "article", "book", "letter"]
        cmd: typst compile --root . template/{{.ITEM}}.typ
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
  acm-suite:
    aliases:
      - acm
    dir: acm-suite
    cmds:
      - for:
          [
            "small",
            "large",
            "manuscript",
            "sigpl",
            "sig-conf",
            "tog",
            "cover-page",
            "engage-cs-edu",
          ]
        cmd: typst compile --root . template/{{.ITEM}}.typ
  upsa-bo:
    dir: upsa-bo
    aliases:
      - upsa
    # watch: true
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
    cmds:
      - for: ["Estudio de Factibilidad", "TFG"]
        cmd: typst compile --root . "template/{{.ITEM}}/{{.ITEM}}.typ"
  butterick:
    dir: butterick-resume
    watch: true
    sources:
      - "**/*.typ"
    generates:
      - "template/*.pdf"
    cmds:
      - typst compile --root . template/main.typ
