#let journals = (
  ACMJCSS: (
    name: [ACM Journal on Computing and Sustainable Societies],
    short-name: [ACM J. Comput. Sustain. Soc.],
    permission-code-1: [2834-5533],
    permission-code-2: [2834-5533],
  ),
  ACMJCDS: (
    name: [ACM Journal of Data Science],
    short-name: [ACM J. Data Sci.],
    permission-code-1: [0000-0000],
    permission-code-2: [0000-0000],
  ),
  AILET: (
    name: [ACM AI Letters],
    short-name: [ACM AI Lett.],
    permission-code-1: [3068-8590],
    permission-code-2: [3068-8590],
  ),
  CIE: (
    name: [ACM Computers in Entertainment],
    short-name: [ACM Comput. Entertain.],
    permission-code-1: [1544-3574],
    permission-code-2: none,
  ),
  CSUR: (
    name: [ACM Computing Surveys],
    short-name: [ACM Comput. Surv.],
    permission-code-1: [0360-0300],
    permission-code-2: [1557-7341],
  ),
  DGOV: (
    name: [Digital Government: Research and Practice],
    short-name: [Digit. Gov. Res. Pract.],
    permission-code-1: [2639-0175],
    permission-code-2: [2639-0175],
  ),
  DLT: (
    name: [Distributed Ledger Technologies: Research and Practice],
    short-name: [Distrib. Ledger Technol.],
    permission-code-1: [2769-6472],
    permission-code-2: [2769-6480],
  ),
  DTRAP: (
    name: [Digital Threats: Research and Practice],
    short-name: [Digit. Threat. Res. Pract.],
    permission-code-1: [2576-5337],
    permission-code-2: [2576-5337],
  ),
  FAC: (
    name: [Formal Aspects of Computing],
    short-name: [Form. Asp. Comput.],
    permission-code-1: [0934-5043],
    permission-code-2: [1433-299X],
  ),
  GAMES: (
    name: [ACM Games: Research and Practice],
    short-name: [ACM Games],
    permission-code-1: [2832-5516],
    permission-code-2: [2832-5516],
  ),
  HEALTH: (
    name: [ACM Transactions on Computing for Healthcare],
    short-name: [ACM Trans. Comput. Healthcare],
    permission-code-1: [2637-8051],
    permission-code-2: [2637-8051],
  ),
  IMWUT: (
    name: [Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies],
    short-name: [Proc. ACM Interact. Mob. Wearable Ubiquitous Technol.],
    permission-code-1: [2474-9567],
    permission-code-2: [2474-9567],
    screen-mode: true,
  ),
  JACM: (
    name: [Journal of the ACM],
    short-name: [J. ACM],
    permission-code-1: [0004-5411],
    permission-code-2: [1557-735X],
  ),
  JATS: (
    name: [Journal on Autonomous Transportation Systems],
    short-name: [ACM J. Auton. Transport. Syst.],
    permission-code-1: [2833-0528],
    permission-code-2: [2833-0528],
  ),
  JDIQ: (
    name: [ACM Journal of Data and Information Quality],
    short-name: [ACM J. Data Inform. Quality],
    permission-code-1: [1936-1955],
    permission-code-2: [1936-1963],
  ),
  JDS: (
    name: [ACM/IMS Journal of Data Science],
    short-name: [ACM/IMS J. Data Sci.],
    permission-code-1: [2831-3194],
    permission-code-2: [2831-3194],
  ),
  JEA: (
    name: [ACM Journal of Experimental Algorithmics],
    short-name: [ACM J. Exp. Algor.],
    permission-code-1: [1084-6654],
    permission-code-2: [1084-6654],
  ),
  JERIC: (
    name: [ACM Journal of Educational Resources in Computing],
    short-name: [ACM J. Edu. Resources in Comput.],
    permission-code-1: [1073-0516],
    permission-code-2: none,
  ),
  JETC: (
    name: [ACM Journal on Emerging Technologies in Computing Systems],
    short-name: [ACM J. Emerg. Technol. Comput. Syst.],
    permission-code-1: [1550-4832],
    permission-code-2: [1550-4840],
  ),
  JOCCH: (
    name: [ACM Journal on Computing and Cultural Heritage],
    short-name: [ACM J. Comput. Cult. Herit.],
    permission-code-1: [1556-4673],
    permission-code-2: [1556-4711],
  ),
  JRC: (
    name: [ACM Journal on Responsible Computing],
    short-name: [ACM J. Responsib. Comput.],
    permission-code-1: [2832-0565],
    permission-code-2: [2832-0565],
  ),
  PACMCGIT: (
    name: [Proceedings of the ACM on Computer Graphics and Interactive Techniques],
    short-name: [Proc. ACM Comput. Graph. Interact. Tech.],
    permission-code-1: [2577-6193],
    permission-code-2: [2577-6193],
    screen-mode: true,
  ),
  PACMHCI: (
    name: [Proceedings of the ACM on Human-Computer Interaction],
    short-name: [Proc. ACM Hum.-Comput. Interact.],
    permission-code-1: [2573-0142],
    permission-code-2: [2573-0142],
    screen-mode: true,
  ),
  PACMMOD: (
    name: [Proceedings of the ACM on Management of Data],
    short-name: [Proc. ACM Manag. Data],
    permission-code-1: [2836-6573],
    permission-code-2: [2836-6573],
  ),
  PACMNET: (
    name: [Proceedings of the ACM on Networkng],
    short-name: [Proc. ACM Netw.],
    permission-code-1: [2834-5509],
    permission-code-2: [2834-5509],
  ),
  PACMPL: (
    name: [Proceedings of the ACM on Programming Languages],
    short-name: [Proc. ACM Program. Lang.],
    permission-code-1: [2475-1421],
    permission-code-2: [2475-1421],
    screen-mode: true,
  ),
  PACMSE: (
    name: [Proceedings of the ACM on Software Engineering],
    short-name: [Proc. ACM Softw. Eng.],
    permission-code-1: [2994-970X],
    permission-code-2: [2994-970X],
    screen-mode: true,
  ),
  POMACS: (
    name: [Proceedings of the ACM on Measurement and Analysis of Computing Systems],
    short-name: [Proc. ACM Meas. Anal. Comput. Syst.],
    permission-code-1: [2476-1249],
    permission-code-2: [2476-1249],
    screen-mode: true,
  ),
  TAAS: (
    name: [ACM Transactions on Autonomous and Adaptive Systems],
    short-name: [ACM Trans. Autonom. Adapt. Syst.],
    permission-code-1: [1556-4665],
    permission-code-2: [1556-4703],
  ),
  TACCESS: (
    name: [ACM Transactions on Accessible Computing],
    short-name: [ACM Trans. Access. Comput.],
    permission-code-1: [1936-7228],
    permission-code-2: [1936-7236],
  ),
  TACO: (
    name: [ACM Transactions on Architecture and Code Optimization],
    short-name: [ACM Trans. Arch. Code Optim.],
    permission-code-1: [1544-3566],
    permission-code-2: [1544-3973],
  ),
  TAIS: (
    name: [ACM Transactions on AI for Science],
    short-name: [ACM Trans. AI Sci.],
    permission-code-1: [3066-4438],
    permission-code-2: [3066-4438],
  ),
  TAISAP: (
    name: [ACM Transactions on AI Security and Privacy],
    short-name: [ACM Trans. AI Secur. Priv.],
    permission-code-1: [3068-3564],
    permission-code-2: [3068-3564],
  ),
  TALG: (
    name: [ACM Transactions on Algorithms],
    short-name: [ACM Trans. Algor.],
    permission-code-1: [1549-6325],
    permission-code-2: [1549-6333],
  ),
  TALLIP: (
    name: [ACM Transactions on Asian and Low-Resource Language Information Processing],
    short-name: [ACM Trans. Asian Low-Resour. Lang. Inf. Process.],
    permission-code-1: [2375-4699],
    permission-code-2: [2375-4702],
  ),
  TAP: (
    name: [ACM Transactions on Applied Perception],
    short-name: [ACM Trans. Appl. Percept.],
    permission-code-1: [1544-3558],
    permission-code-2: [1544-3965],
  ),
  TCPS: (
    name: [ACM Transactions on Cyber-Physical Systems],
    short-name: [ACM Trans. Cyber-Phys. Syst.],
    permission-code-1: [2378-962X],
    permission-code-2: [2378-9638],
  ),
  TDS: (
    name: [ACM/IMS Transactions on Data Science],
    short-name: [ACM/IMS Trans. Data Sci.],
    permission-code-1: [2577-3224],
    permission-code-2: none,
  ),
  TEAC: (
    name: [ACM Transactions on Economics and Computation],
    short-name: [ACM Trans. Econ. Comput.],
    permission-code-1: [2167-8375],
    permission-code-2: [2167-8383],
  ),
  TECS: (
    name: [ACM Transactions on Embedded Computing Systems],
    short-name: [ACM Trans. Embedd. Comput. Syst.],
    permission-code-1: [1539-9087],
    permission-code-2: [1558-3465],
  ),
  TELO: (
    name: [ACM Transactions on Evolutionary Learning and Optimization],
    short-name: [ACM Trans. Evol. Learn. Optim.],
    permission-code-1: [2688-299X],
    permission-code-2: [2688-3007],
  ),
  THRI: (
    name: [ACM Transactions on Human-Robot Interaction],
    short-name: [ACM Trans. Hum.-Robot Interact.],
    permission-code-1: [2573-9522],
    permission-code-2: [2573-9522],
  ),
  TIIS: (
    name: [ACM Transactions on Interactive Intelligent Systems],
    short-name: [ACM Trans. Interact. Intell. Syst.],
    permission-code-1: [2160-6455],
    permission-code-2: [2160-6463],
  ),
  TIOT: (
    name: [ACM Transactions on Internet of Things],
    short-name: [ACM Trans. Internet Things],
    permission-code-1: [2577-6207],
    permission-code-2: [2577-6207],
  ),
  TISSEC: (
    name: [ACM Transactions on Information and System Security],
    short-name: [ACM Trans. Info. Syst. Sec.],
    permission-code-1: [1094-9224],
    permission-code-2: none,
  ),
  TIST: (
    name: [ACM Transactions on Intelligent Systems and Technology],
    short-name: [ACM Trans. Intell. Syst. Technol.],
    permission-code-1: [2157-6904],
    permission-code-2: [2157-6912],
  ),
  TKDD: (
    name: [ACM Transactions on Knowledge Discovery from Data],
    short-name: [ACM Trans. Knowl. Discov. Data.],
    permission-code-1: [1556-4681],
    permission-code-2: [1556-472X],
  ),
  TMIS: (
    name: [ACM Transactions on Management Information Systems],
    short-name: [ACM Trans. Manag. Inform. Syst.],
    permission-code-1: [2158-656X],
    permission-code-2: [2158-6578],
  ),
  TOCE: (
    name: [ACM Transactions on Computing Education],
    short-name: [ACM Trans. Comput. Educ.],
    permission-code-1: [1946-6226],
    permission-code-2: [1946-6226],
  ),
  TOCHI: (
    name: [ACM Transactions on Computer-Human Interaction],
    short-name: [ACM Trans. Comput.-Hum. Interact.],
    permission-code-1: [1073-0516],
    permission-code-2: [1557-7325],
  ),
  TOCL: (
    name: [ACM Transactions on Computational Logic],
    short-name: [ACM Trans. Comput. Logic],
    permission-code-1: [1529-3785],
    permission-code-2: [1557-945X],
  ),
  TOCS: (
    name: [ACM Transactions on Computer Systems],
    short-name: [ACM Trans. Comput. Syst.],
    permission-code-1: [0734-2071],
    permission-code-2: [1557-7333],
  ),
  TOCT: (
    name: [ACM Transactions on Computation Theory],
    short-name: [ACM Trans. Comput. Theory],
    permission-code-1: [1942-3454],
    permission-code-2: [1942-3462],
  ),
  TODAES: (
    name: [ACM Transactions on Design Automation of Electronic Systems],
    short-name: [ACM Trans. Des. Autom. Electron. Syst.],
    permission-code-1: [1084-4309],
    permission-code-2: [1557-7309],
  ),
  TODS: (
    name: [ACM Transactions on Database Systems],
    short-name: [ACM Trans. Datab. Syst.],
    permission-code-1: [0362-5915],
    permission-code-2: [1557-4644],
  ),
  TOG: (
    name: [ACM Transactions on Graphics],
    short-name: [ACM Trans. Graph.],
    permission-code-1: [0730-0301],
    permission-code-2: [1557-7368],
  ),
  TOIS: (
    name: [ACM Transactions on Information Systems],
    short-name: [ACM Trans. Inf. Syst.],
    permission-code-1: [1046-8188],
    permission-code-2: [1558-2868],
  ),
  TOIT: (
    name: [ACM Transactions on Internet Technology],
    short-name: [ACM Trans. Internet Technol.],
    permission-code-1: [1533-5399],
    permission-code-2: [1557-6051],
  ),
  TOMACS: (
    name: [ACM Transactions on Modeling and Computer Simulation],
    short-name: [ACM Trans. Model. Comput. Simul.],
    permission-code-1: [1049-3301],
    permission-code-2: [1558-1195],
  ),
  TOMM: (
    name: [ACM Transactions on Multimedia Computing, Communications and Applications],
    short-name: [ACM Trans. Multimedia Comput. Commun. Appl.],
    permission-code-1: [1551-6857],
    permission-code-2: [1551-6865],
  ),
  TOMPECS: (
    name: [ACM Transactions on Modeling and Performance Evaluation of Computing Systems],
    short-name: [ACM Trans. Model. Perform. Eval. Comput. Syst.],
    permission-code-1: [2376-3639],
    permission-code-2: [2376-3647],
  ),
  TOMS: (
    name: [ACM Transactions on Mathematical Software],
    short-name: [ACM Trans. Math. Softw.],
    permission-code-1: [0098-3500],
    permission-code-2: [1557-7295],
  ),
  TOPC: (
    name: [ACM Transactions on Parallel Computing],
    short-name: [ACM Trans. Parallel Comput.],
    permission-code-1: [2329-4949],
    permission-code-2: [2329-4957],
  ),
  TOPLAS: (
    name: [ACM Transactions on Programming Languages and Systems],
    short-name: [ACM Trans. Program. Lang. Syst.],
    permission-code-1: [0164-0925],
    permission-code-2: [1558-4593],
  ),
  TOPML: (
    name: [ACM Transactions on Probabilistic Machine Learning],
    short-name: [ACM Trans. Probab. Mach. Learn.],
    permission-code-1: [2836-8924],
    permission-code-2: [2836-8924],
  ),
  TOPS: (
    name: [ACM Transactions on Privacy and Security],
    short-name: [ACM Trans. Priv. Sec.],
    permission-code-1: [2471-2566],
    permission-code-2: [2471-2574],
  ),
  TORS: (
    name: [ACM Transactions on Recommender Systems],
    short-name: [ACM Trans. Recomm. Syst.],
    permission-code-1: [2770-6699],
    permission-code-2: [2770-6699],
  ),
  TOS: (
    name: [ACM Transactions on Storage],
    short-name: [ACM Trans. Storage],
    permission-code-1: [1553-3077],
    permission-code-2: [1553-3093],
  ),
  TOSEM: (
    name: [ACM Transactions on Software Engineering and Methodology],
    short-name: [ACM Trans. Softw. Eng. Methodol.],
    permission-code-1: [1049-331X],
    permission-code-2: [1557-7392],
  ),
  TOSN: (
    name: [ACM Transactions on Sensor Networks],
    short-name: [ACM Trans. Sensor Netw.],
    permission-code-1: [1550-4859],
    permission-code-2: [1550-4867],
  ),
  TQC: (
    name: [ACM Transactions on Quantum Computing],
    short-name: [ACM Trans. Quantum Comput.],
    permission-code-1: [2643-6817],
    permission-code-2: [2643-6817],
  ),
  TRETS: (
    name: [ACM Transactions on Reconfigurable Technology and Systems],
    short-name: [ACM Trans. Reconfig. Technol. Syst.],
    permission-code-1: [1936-7406],
    permission-code-2: [1936-7414],
  ),
  TSAS: (
    name: [ACM Transactions on Spatial Algorithms and Systems],
    short-name: [ACM Trans. Spatial Algorithms Syst.],
    permission-code-1: [2374-0353],
    permission-code-2: [2374-0361],
  ),
  TSC: (
    name: [ACM Transactions on Social Computing],
    short-name: [ACM Trans. Soc. Comput.],
    permission-code-1: [2469-7818],
    permission-code-2: [2469-7826],
  ),
  TSLP: (
    name: [ACM Transactions on Speech and Language Processing],
    short-name: [ACM Trans. Speech Lang. Process.],
    permission-code-1: [1550-4875],
    permission-code-2: [2329-9304],
  ),
  TWEB: (
    name: [ACM Transactions on the Web],
    short-name: [ACM Trans. Web],
    permission-code-1: [1559-1131],
    permission-code-2: [1559-114X],
  ),
  FACMP: (
    name: [ACM Just Accepted],
    short-name: [ACM Accepted],
    permission-code-1: [XXXX-XXXX],
    permission-code-2: none,
  ),
)

#let journal-keys = journals.keys()
